2018-05-11 13:40:22,260 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-11 13:41:11,501 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-11 13:41:18,069 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-11 13:42:52,617 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-11 13:43:04,287 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-11 13:43:50,308 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 09:22:09,876 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 09:32:30,873 ERROR: Exception on /search [POST] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 101, in search
    form.bp.data, form.verantwoordelijke.data, form.in_scope.data)
  File "D:\flask\stageopdracht\app\my_scribbles.py", line 339, in search_db
    return repositories, modules
UnboundLocalError: local variable 'repositories' referenced before assignment
2018-05-14 10:06:10,368 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:06:42,244 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:28:45,600 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:29:36,839 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:30:25,318 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:32:28,157 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:36:31,507 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:40:01,172 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:40:19,805 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:41:12,898 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:41:36,625 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:42:09,265 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:42:28,474 ERROR: Exception on /testing [GET] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 220, in testing
    title="testing")
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\flask\stageopdracht\app\templates\testing.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\flask\stageopdracht\app\templates\base.html", line 32, in top-level template code
    {% block content %} {% endblock %}
  File "D:\flask\stageopdracht\app\templates\testing.html", line 5, in block "content"
    <div>{{ form.rating.label }}</div>
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2018-05-14 10:44:00,111 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:46:16,983 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:47:06,482 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 10:50:00,335 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 11:04:43,634 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 11:05:37,938 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 11:32:54,759 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 11:33:42,795 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 11:35:36,571 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
2018-05-14 11:39:54,429 ERROR: Exception on /testing [GET] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 220, in testing
    title="testing")
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\flask\stageopdracht\app\templates\testing.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\flask\stageopdracht\app\templates\base.html", line 32, in top-level template code
    {% block content %} {% endblock %}
  File "D:\flask\stageopdracht\app\templates\testing.html", line 5, in block "content"
    <div>{{ form.rating.label }}</div>
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2018-05-14 11:43:24,824 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:39]
