2018-05-16 16:30:52,957 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:31:22,832 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:32:56,820 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:38:16,029 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:43:02,985 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:43:49,571 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:45:31,327 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:47:20,078 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:56:14,389 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-16 16:57:54,545 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-17 09:18:47,142 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-17 09:22:03,462 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-17 09:22:10,319 ERROR: Exception on /search_repository [POST] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 115, in search_repository
    repositories = search_repository(form.repository.data, form.bp.data, form.in_scope.data)
TypeError: search_repository() takes 0 positional arguments but 3 were given
2018-05-17 09:25:50,702 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-17 09:25:58,517 ERROR: Exception on /search_module [POST] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 93, in search_module
    modules = search_module_f(form.module.data, form.search_version.data,
AttributeError: 'SearchModuleForm' object has no attribute 'search_version'
2018-05-17 09:26:50,745 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-17 09:26:57,551 ERROR: Exception on /search_module [POST] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 106, in search_module
    rating=rating, review=review, readme=readme)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: search_results_module
2018-05-17 09:27:24,580 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-17 09:28:44,570 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-17 09:31:36,770 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-17 09:32:55,648 INFO: App startup [in D:\flask\stageopdracht\app\__init__.py:33]
2018-05-17 09:33:10,284 ERROR: Exception on /version_details/account-analytic/8 [GET] [in d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flask\stageopdracht\app\routes.py", line 57, in version_details
    form=form)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "d:\flask\stageopdracht\venv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\flask\stageopdracht\app\templates\version_details.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\flask\stageopdracht\app\templates\base.html", line 20, in top-level template code
    {% block content %} {% endblock %}
  File "D:\flask\stageopdracht\app\templates\version_details.html", line 3, in block "content"
    <div><p>Selected version: {{ version_x }} <br> Current Repository: {{ modules[0].repo_name }}</p></div>
  File "d:\flask\stageopdracht\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: None has no element 0
